config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    resources :users, only: %i[index edit update destroy]
    resources :posts, only: :index
    resources :genres, only: %i[index edit create update destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  scope module: :users do
    root 'homes#top'
    get 'inquiries' => 'inquiries#inquiries', as: 'inquiries'
    post 'inquiries' => 'inquiries#mail'
    get 'done' => 'inquiries#done', as: 'done'
    get 'users/mypage' => 'users#show', as: 'mypage'
    get 'users/leave' => 'users#leave'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update'
    get 'posts/ranks' => 'posts#rank'
    get 'posts/tags' => 'posts#tag'
    resources :posts do
      resources :comments, only: %i[edit create update destroy]
      resource :favorites, only: %i[create destroy]
    end

    get 'tag_search' => 'posts#tag_search'
    get 'search' => 'posts#search'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_images
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :genre

  accepts_attachments_for :post_images, attachment: :image
  acts_as_taggable

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # def self.sort(selection)
  #   case selection
  #   when "new"
  #     return all.order(created_at: :DESC)
  #   when "old"
  #     return all.order(created_ad: :ASC)
  #   when "favorites"
  #     return find(Favorite.group(:post_id).order(Arel.sql("count(post_id) desc")).pluck(:post_id))
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :favorites

  validates :name, presence: true
  validates :nickname, presence: true

  def self.guest
    user = User.new(email: "#{SecureRandom.alphanumeric}@example.com", password: SecureRandom.urlsafe_base64,
                    name: 'guest5gbcyjsozzkdyyb6', nickname: 'guest')
    user.save
    User.last
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: "DESC").page(params[:page]).per(30)
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin

  def index
    @users = User.all.order(created_at: 'DESC').page(params[:page]).per(30)
    @guest_user = User.where(name: 'guest5gbcyjsozzkdyyb6')
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admins_users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.where(name: 'guest5gbcyjsozzkdyyb6')
    @user.destroy_all
    redirect_back(fallback_location: root_path)
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :profile, :is_deleted)
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  before_action :authenticate_user

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    @comment.save
    render :index
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(id: params[:id], post_id: params[:post_id])
    @comment.destroy
    render :index
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  before_action :authenticate_user

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  def top
    @genres = Genre.all
    @posts_rank = Post.find(Favorite.group(:post_id).order('count(post_id)desc').limit(9).pluck(:post_id))
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(9)
  end
end

app/controllers/users/inquiries_controller.rb
class Users::InquiriesController < ApplicationController
  before_action :authenticate_user, only: %i[mail done]
  before_action :authenticate_guest_user, only: %i[mail done]

  def inquiries
    @inquiry = Inquiry.new
  end

  def mail
    inquiry = Inquiry.new(inquiry_params)
    if (inquiry.name != '') && (inquiry.message != '')
      inquiry.email = current_user.email if user_signed_in? && (current_user.name != 'guest5gbcyjsozzkdyyb6')
      InquiryMailer.send_mail(inquiry).deliver_now
      redirect_to done_path
    else
      render :inquiries
    end
  end

  def done; end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :message)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController

  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :authenticate_guest_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.score = Language.get_data(post_params[:body])
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @tags = Post.tags_on(:tags)
    @q = Post.ransack(params[:q])
    @genres = Genre.all
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @no_genres = Genre.where.not(id: @genre.id)
      @posts_all = Post.where(genre_id: @genre.id).order(created_at: "DESC").page(params[:page]).per(18)
    else
      @posts = @q.result(distinct: true)
      @posts_all = @posts.order(created_at: "DESC").page(params[:page]).per(18)
    end
  end

  def rank
    @genres = Genre.all
    @q = Post.ransack(params[:q])
    @tags = Post.tags_on(:tags)
    @genres = Genre.all
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @no_genres = Genre.where.not(id: @genre.id)
      @posts = Favorite.joins(:post).where(posts: {genre_id: params[:genre_id]}).group(:post_id).order("count(post_id) desc").limit(15).pluck(:post_id)
      @all_ranks = Post.find(@posts)
    else
      @all_ranks = Post.find(Favorite.group(:post_id).order("count(post_id)desc").limit(15).pluck(:post_id))
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.user.id)
    @comment = Comment.new
    @comments_all = Comment.all
    @tags = @post.tag_counts_on(:tags)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def tag
    @q = Post.ransack(params[:q])
    # タグをPostモデルから降順で取得
    @tags = Post.tag_counts_on(:tags).order(created_at: :desc)
    if @tag = params[:tag]
      # タグに紐付く投稿 　tagged_with 絞り込み検索するメソッド
      @tags_all = Post.tags_on(:tags)
      @posts = Post.tagged_with(params[:tag])
      @posts_all = @posts.order(created_at: "DESC").page(params[:page]).per(20)
    end
  end

  private


  def post_params
    params.require(:post).permit(:user_id, :genre_id, :title, :body, :price, :address, :tag_list, post_images_images:[])
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/searches_controller.rb
class Users::SearchesController < ApplicationController
  def search; end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email])
    if @user && (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
      redirect_to new_user_session_path
    end
  end

  def after_sign_in_path_for(_resource)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user
  before_action :authenticate_guest_user

  def show
    @user = current_user
    @posts = Post.where(user_id: @user.id)
    @favorites = Favorite.where(user_id: @user.id)
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path
    else
      render :edit
    end
  end

  def leave
    @user = current_user
  end

  def withdraw
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :nickname, :profile)
  end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/posts/_form.html.erb
<div class="post-content">
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <p class="message-text"><i class="fas fa-exclamation-triangle"></i> <%= message %></p>
    <% end %>
  <% end %>
  <%= form_with model:post, local: true do |f| %>
    <table class="table table-borderless">
        <tr>
          <td>画像</td>
          <td><%= f.attachment_field :post_images_images, multiple: true %></td>
        </tr>
        <tr>
          <td colspan="2">(画像サイズによって正しく表示されない場合があります)</td>
        </tr>
        <tr>
          <td>プレビュー</td>
          <td>
            <img id="preview_0" style="width:15%;">
            <img id="preview_1" style="width:15%;">
            <img id="preview_2" style="width:15%;">
            <img id="preview_3" style="width:15%;">
            <img id="preview_4" style="width:15%;">
          </td>
        </tr>
        <tr>
          <td>タイトル</td>
          <td><%= f.text_field :title, class:"col-6" %></td>
        </tr>
        <tr>
          <td>詳細</td>
          <td><%= f.text_area :body, rows:"5", class:"col-6" %></td>
        </tr>
        <tr>
          <td>ターゲット</td>
          <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %></td>
        </tr>
        <tr>
          <td>価格</td>
          <td><%= f.text_area :price, class:"col-6" %></td>
        </tr>
        <tr>
          <td>所在地</td>
          <td><%= f.text_field :address, class:"col-6" %></td>
        </tr>
        <tr>
          <td>タグ</td>
          <td>
            <%= f.text_field :tag_list, value: post.tag_list.join(','), class:"col-6", placeholder: "複数付ける場合は「,」で区切ってください" %>
          </td>
        </tr>
          <td></td>
        <tr>
          <td><%= f.submit submit, class:btn %></td>
        </tr>
    </table>
  <% end %>
</div>

app/views/users/posts/_search_form.html.erb
<div class="posts-searches">
  <div class="posts-search">
    <%= search_form_for q do |f| %>
      <%= f.search_field :title_cont, class:"posts-search-field"%>
      <div class="posts-search-btn">
        <%= f.submit " 検索 ", class:"btn btn-blue" %>
      </div>
    <% end %>
  </div>
  <% if tags.present? %>
    <!--投稿についているタグを表示-->
    <div class="posts-search-tags">
      <% tags.each do |tag| %>
        <%= link_to "#{tag.name}(#{tag.taggings_count})", posts_tags_path(tag: tag.name) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/posts/_search_result.html.erb
<div class="posts">
  <div class="post article-list">
  <% posts.each do |post| %>
    <div class="post-content">
      <div class="post-index-image">
        <%= link_to post_path(post.id) do %>
          <%= attachment_image_tag post.post_images[0], :image, :fill, 400, 330, fallback: "no_image.png", size:"400x330" %>
        <% end %>
      </div>
      <div class="post-text">
        <h3><%= post.title %></h3>
        <div class="post-genre-like">
        <h5><%= post.genre.name %></h5>
        <p class="likes"><%= image_tag "favorite2.png" %><%= post.favorites.count %></p>
        </div>
        <p><%= post.created_at.strftime("%Y/%m/%d") %></p>
      </div>
    </div>
  <% end %>
  </div>
  <div class="row mt-5">
    <div class="mx-auto">
    <%= paginate posts %>
    </div>
  </div>
</div>

app/views/users/posts/edit.html.erb
<div class="post-edit">
  <h1><i class="far fa-edit"></i> 編集</h1>
  <%= render "form", post: @post, submit: "更新", btn: "btn btn-green" %>
  <%= link_to post_path(@post.id), method: :delete, class:"btn btn-red", data: {confirm: "削除しますか？"} do %>
    <i class="fas fa-exclamation-triangle"></i> 投稿を削除する
  <% end %>
</div>

app/views/users/posts/genre.html.erb
<div class="posts-genre">
  <div class="posts-searches">
    <div class="posts-search">
      <%= search_form_for @q do |f| %>
        検索
        <%= f.search_field :title_cont, class:"col-8" %>
        <%= f.submit " 検索 " %>
      <% end %>
    </div>
  </div>


  <%= render "search_result", posts: @posts_all %>
</div>

app/views/users/posts/index.html.erb
<div class="posts-index">
  <% if @genre.present? %>
    <h1><i class="fas fa-kiwi-bird"></i> <%= @genre.name %></h1>
    <div class="posts-index-link">
      <% @no_genres.each do |genre| %>
        <div class="posts-index-genre-btn">
          <%= link_to posts_path(genre_id: genre.id) do %>
            <i class="fas fa-hand-point-right"></i> <%= genre.name %>はこちら
          <% end %>
        </div>
      <% end %>
      <div class="posts-index-btn">
        <%= link_to posts_path do %>
          <i class="fas fa-hand-point-right"></i> 全ての投稿はこちら
        <% end %>
      </div>
    <% else %>
      <h1><i class="fas fa-kiwi-bird"></i> 全ての投稿</h1>
      <% @genres.each do |genre| %>
        <div class="posts-index-genre-btn">
          <%= link_to posts_path(genre_id: genre.id) do %>
            <i class="fas fa-hand-point-right"></i> <%= genre.name %>はこちら
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= render "search_form", q: @q, tags: @tags %>
  <%= render "search_result", posts: @posts_all %>
</div>

app/views/users/posts/new.html.erb
<div class="post-new">
  <h1>新規投稿<i class="fas fa-feather"></i></h1>
  <%= render "form", post: @post, submit: "新規登録", btn: "btn btn-green" %>
</div>

app/views/users/posts/rank.html.erb
<div class="posts-rank">
  <% if @genre.present? %>
    <h1><i class="fas fa-crown"></i> <%= @genre.name %>のランキング</h1>
  <% else %>
    <h1><i class="fas fa-crown"></i> 全体のランキング</h1>
  <% end %>
  <% if @genre.present? %>
    <div class="posts-index-link">
      <% @no_genres.each do |genre| %>
        <div class="posts-index-genre-btn">
          <%= link_to posts_ranks_path(genre_id: genre.id) do %>
            <i class="fas fa-hand-point-right"></i> <%= genre.name %>のランキングはこちら
          <% end %>
        </div>
      <% end %>
      <div class="posts-index-btn">
        <%= link_to posts_ranks_path do %>
          <i class="fas fa-hand-point-right"></i> 全てのランキングはこちら
        <% end %>
      </div>
    <% else %>
      <% @genres.each do |genre| %>
        <div class="posts-index-genre-btn">
          <%= link_to posts_ranks_path(genre_id: genre.id) do %>
            <i class="fas fa-hand-point-right"></i> <%= genre.name %>のランキングはこちら
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= render "search_form", q: @q, tags: @tags %>
  <div class="post article-list">
    <% @all_ranks.each.with_index(1) do |post, i| %>
     <div class="post-content">
       <h4>第 <%= i %> 位</h4>
      <div class="post-image">
        <%= link_to post_path(post.id) do %>
          <%= attachment_image_tag post.post_images[0], :image, :fill, 400, 330, fallback: "no_image.png", size:"400x330" %>
        <% end %>
      </div>
      <div class="post-text">
        <h4><%= post.title %></h4>
        <div class="post-genre-like">
        <p><%= post.genre.name %></p>
        <p class="likes"><%= image_tag "favorite2.png" %><%= post.favorites.count %></p>
        </div>
        <p><%= post.created_at.strftime("%Y/%m/%d") %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/posts/search.html.erb
<div class="container">
  <h1>検索結果</h1>

  <%= render "search_result", posts: @posts_search %>
</div>

app/views/users/posts/show.html.erb
<div class="main">
  <div class="post-show-images">
    <% if @post.post_images.present? %>
      <div class="post-show-images-slick">
        <% @post.post_images.each do |image| %>
          <div class="post-show-image">
            <%= attachment_image_tag image, :image %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="post-show-no">
        <%= image_tag "no_image.png", class:"post-show-no-image" %>
      </div>
    <% end %>
  </div>
  <div class="post-details">
    <h2><%= @post.title %></h2>
    <!--signinしている場合のみいいね可能-->
    <div class="post-time-likes">
    <p>
      <%= @post.user.name %>  <%= @post.created_at.strftime("%Y/%m/%d") %></br>
      <%= @post.genre.name %>
    </p>
    <% if user_signed_in? %>
      <div class="favorites-btn-<%= @post.id %>">
        <!--いいね機能の部分テンプレート-->
        <%= render "users/favorites/favorites-btn", { post: @post} %>
      </div>
    <% else %>
        <p class="likes"><%= image_tag "favorite2.png" %><%= @post.favorites.count %></p>
    <% end %>
    </div>
  </div>
  <% if @tags.present? %>
  <!--投稿についているタグを表示-->
    <div class="post-show-tags">
      <% @tags.each do |tag| %>
        <%= link_to "#{tag.name}(#{tag.taggings_count})", posts_tags_path(tag: tag.name) %>
      <% end %>
    </div>
  <% end %>
  <table class="table table-border">
    <% if @post.body.present? %>
    <tr>
      <td class="table-active">詳細</td>
      <td><%= @post.body %></td>
    </tr>
    <% end %>
    <% if @post.price.present? %>
    <tr>
      <td class="table-active">価格</td>
      <td><%= @post.price %></td>
    </tr>
    <% end %>
    <% if @post.address.present? %>
    <tr>
      <td class="table-active">所在地</td>
      <td><%= @post.address %></td>
    </tr>
    <% end %>
  </table>
  <!--signinしている場合のみ投稿編集可能-->
    <% if user_signed_in? %>
      <% if current_user.id == @post.user_id %>
        <%= link_to "投稿を編集する", edit_post_path(@post.id), class:"btn btn-green" %>
      <% end %>
    <% elsif admin_signed_in? %>
      <%= link_to "投稿を削除する", post_path(@post.id), method: :delete, class:"btn btn-red", data: {confirm: "削除しますか？"} %>
    <% end %>
    <!--signinしている場合のみフォーム表示-->
    <% if user_signed_in? %>
      <h4 class="comment-form-btn comment-btn">　コメント入力フォーム　<i class="fas fa-chevron-circle-down"></i></h4>
        <!--コメントフォームの部分テンプレート-->
      <div class="comment-form">
        <%= render partial: "users/comments/comments-form", locals: { post: @post, comment: @comment } %>
      </div>
    <% end %>
  <h4 class="comment-index-btn comment-btn">　コメント一覧　<i class="fas fa-chevron-circle-down"></i></h4>
  <div class="comment-index">
    <!--コメント一覧の部分テンプレート-->
    <%= render partial: "users/comments/comments-index", locals: { post: @post } %>
  </div>
</div>

app/views/users/posts/tag.html.erb
<div class="posts-tag">
<% if @posts_all.present? %>
    <h1><i class="fas fa-kiwi-bird"></i> 「<%= @tag %>」に関連する投稿</h1>
    <%= render "search_form", q: @q, tags: @tags_all %>
    <%= render "search_result", posts: @posts_all %>
<% end %>
</div>

app/views/users/posts/tag_search.html.erb
<div class="container">
  <h1>検索結果</h1>

  <%= render "search_form", post: @post %>

  <%= render "search_result", posts: @posts %>

</div>