config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    resources :users, only: %i[index edit update destroy]
    resources :posts, only: :index
    resources :genres, only: %i[index edit create update destroy]
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

  scope module: :users do
    root 'homes#top'
    get 'inquiries' => 'inquiries#inquiries', as: 'inquiries'
    post 'inquiries' => 'inquiries#mail'
    get 'done' => 'inquiries#done', as: 'done'
    get 'users/mypage' => 'users#show', as: 'mypage'
    get 'users/leave' => 'users#leave'
    patch 'users/withdraw' => 'users#withdraw'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update'
    get 'posts/ranks' => 'posts#rank'
    get 'posts/tags' => 'posts#tag'
    resources :posts do
      resources :comments, only: %i[edit create update destroy]
      resource :favorites, only: %i[create destroy]
    end

    get 'tag_search' => 'posts#tag_search'
    get 'search' => 'posts#search'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :message, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_images
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :genre

  accepts_attachments_for :post_images, attachment: :image
  acts_as_taggable

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # def self.sort(selection)
  #   case selection
  #   when "new"
  #     return all.order(created_at: :DESC)
  #   when "old"
  #     return all.order(created_ad: :ASC)
  #   when "favorites"
  #     return find(Favorite.group(:post_id).order(Arel.sql("count(post_id) desc")).pluck(:post_id))
  #   end
  # end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :favorites

  validates :name, presence: true
  validates :nickname, presence: true

  def self.guest
    user = User.new(email: "#{SecureRandom.alphanumeric}@example.com", password: SecureRandom.urlsafe_base64,
                    name: 'guest5gbcyjsozzkdyyb6', nickname: 'guest')
    user.save
    User.last
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # 管理者側バリデーション
  def authenticate_admin
    redirect_to new_admin_session_path if current_admin.nil?
  end

  # 会員側バリデーション
  def authenticate_user
    redirect_to new_user_session_path if current_user.nil? && current_admin.nil?
  end

  # ゲストユーザー側バリテーション
  def authenticate_guest_user
    redirect_to root_path unless current_user.nil? && (current_user.name == 'guest5gbcyjsozzkdyyb6')
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name nickname])
  end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/search_helper.rb
module Users::SearchHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-logo">
    <%= link_to inquiries_path do %>
      <i class="far fa-envelope"></i> お問い合わせ
    <% end %>
  </div>
  <div>
    <ul class="footer-list">
      <% if user_signed_in? %>
        <% if current_user.name == "guest5gbcyjsozzkdyyb6" %>
          <li><%= link_to "Posts", posts_path %></li>
          <li><%= link_to "Ranking", posts_ranks_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "NewPost", new_post_path %></li>
          <li><%= link_to "Posts", posts_path %></li>
          <li><%= link_to "Ranking", posts_ranks_path %></li>
          <li><%= link_to "Mypage", mypage_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% end %>
      <% elsif admin_signed_in? %>
        <li><%= link_to "Posts", admins_posts_path %></li>
        <li><%= link_to "Users", admins_users_path %></li>
        <li><%= link_to "Genres", admins_genres_path %></li>
        <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Top", root_path %></li>
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "Ranking", posts_ranks_path %></li>
        <li><%= link_to "GuestLogin", users_guest_sign_in_path, method: :post %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "SignUp", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header-hello">
  <% if user_signed_in? %>
    <% if current_user.name == "guest5gbcyjsozzkdyyb6" %>
      <p><i class="fas fa-crow"></i> ゲストユーザーとしてログイン中です</p>
    <% else %>
      <p><i class="fas fa-dove"></i> こんにちは、<%= current_user.nickname %>さん</p>
    <% end %>
  <% end %>
</div>
<div class="header-logo">
  <%= link_to "/" do %>
    <%= image_tag "Tottottrip_logo.png", :size => "200x70" %>
  <% end %>
</div>

<div class="openbtn"><span></span><span></span><span></span></div>
<nav id="g-nav">
  <div id="g-nav-list">
    <ul>
      <% if user_signed_in? %>
        <% if current_user.name == "guest5gbcyjsozzkdyyb6" %>
          <li><%= link_to "投稿一覧", posts_path %></li>
          <li><%= link_to "ランキング", posts_ranks_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規投稿", new_post_path %></li>
          <li><%= link_to "投稿一覧", posts_path %></li>
          <li><%= link_to "ランキング", posts_ranks_path %></li>
          <li><%= link_to "マイページ", mypage_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% end %>
      <% elsif admin_signed_in? %>
        <li><%= link_to "投稿一覧", admins_posts_path %></li>
        <li><%= link_to "会員一覧", admins_users_path %></li>
        <li><%= link_to "ジャンル一覧", admins_genres_path %></li>
        <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Top", root_path %></li>
        <li><%= link_to "投稿一覧", posts_path %></li>
        <li><%= link_to "ランキング", posts_ranks_path %></li>
        <li><%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>
<div class="circle-bg"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tottottrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://rawgit.com/kimmobrunfeldt/progressbar.js/master/dist/progressbar.min.js"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <% if current_page?(root_path) %>
      <div id="splash">
        <div id="splash_text"></div>
      </div>
    <% end %>
    <header>
      <%= render "layouts/header" %>
    </header>
    <% if current_page?(root_path) %>
      <%= yield %>
    <% else %>
      <main>
        <%= yield %>
      </main>
    <% end %>
    <footer>
      <p id="page-top"><a href="#"></a></p>
    </div>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>